name: Superpickaxe
version: 0.1
author: DiddiZ
website: http://diddiz.insane-architects.net/
main: de.diddiz.Superpickaxe.Superpickaxe
description: Adds a simple super pickaxe.
commands:
  spa:
    description: 'Enables or disables super pickaxe'
    usage: 'Usage: /<command>'
    aliases: []