name: Superpickaxe
version: 0.4e
author: DiddiZ
website: http://diddiz.insane-architects.net/
main: de.diddiz.superpickaxe.Superpickaxe
description: Adds a simple super pickaxe.
softdepend: [LogBlock, WorldEdit, Permissions]
commands:
  spa:
    description: 'Enables or disables super pickaxe'
    usage: 'Usage: /<command>'
    aliases: []
permissions:
    superpickaxe.*:
        description: Gives access to all SuperPickaxe commands
        children:
            superpickaxe.use: true
            superpickaxe.breakAll: true
    superpickaxe.use:
        description: 'Allows to use the super pickaxe'
        default: op
    superpickaxe.breakAll:
        description: 'Allows to ignore dontBreak listed blocks'
        default: op
